dist: focal

sudo: required

language: node_js

node_js:
  - 18.4.0

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"

script:
  - docker image prune --all -f
  - docker-compose -f docker-compose-build.yaml build --parallel

  #Tagging
  - docker tag udagram-api-feed mharyam/udagram-api-feed:v4
  - docker tag udagram-api-user mharyam/udagram-api-user:v4
  - docker tag udagram-frontend mharyam/udagram-frontend:v4
  - docker tag udagram-reverseproxy mharyam/udagram-reverseproxy:v4

  #PUSH
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mharyam/udagram-api-feed:v4
  - docker push mharyam/udagram-api-user:v4
  - docker push mharyam/udagram-frontend:v4
  - docker push mharyam/udagram-reverseproxy:v4
