apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: udagram-api-feed
        image: mharyam/udagram-api-feed
        ports:
        - containerPort: 80
      - name: udagram-api-user
        image: mharyam/udagram-api-user
        ports:
          - containerPort: 80
      - name: udagram-frontend
        image: mharyam/udagram-frontend
        ports:
          - containerPort: 80
      - name: udagram-reverseproxy
        image: mharyam/udagram-reverseproxy
        ports:
          - containerPort: 80

      imagePullSecrets:
        - name: dockersecret