apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
        - name: udagram-reverseproxy
          image: mharyam/udagram-reverseproxy:v4
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always